"""VectorBackend protocol (Item 2).

The storage-agnostic contract the engine relies on. It is exactly the surface the original
in-memory ``TasteGraphIndex`` exposed, so any backend (in-memory numpy, Qdrant, FAISS) is a
drop-in.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional, Protocol, Union, runtime_checkable

PathLike = Union[str, Path]


@runtime_checkable
class VectorBackend(Protocol):
    def add(self, asset_id: str, vector) -> None: ...
    def remove(self, asset_id: str) -> bool: ...
    def __contains__(self, asset_id: str) -> bool: ...
    def __len__(self) -> int: ...
    def vector(self, asset_id: str): ...
    def knn(self, query, k: int = 10, exclude: Optional[set] = None) -> list[tuple[str, float]]: ...
    def score_ids(self, query, asset_ids: list[str]) -> dict[str, float]: ...
    def save(self, path: PathLike) -> None: ...
